### ISSUE TITLE
Robust image alignement for multiplexed images

### ISSUE THREAD

**Issue by ggut** [pelkmanslab/TissueMAPS-OLD#13]
The current image alignment for multiplexing projects struggles with low DAPI intensities or bright, non- cell debris.  It is important to ensure proper alignment of the images over all cycles. 

I forwarded a solution, implemented in Matlab, to this problem to Ale.

**Comment by alecrimi** [comment]
This is not a standard way of reporting an issue as it is unreadable to external reader, please use standard style.

**Comment by alecrimi** [comment]
I am trying a test experiment with multiplexing data.
The pipeline reaches the "image pre-processing" step and it returns "STOPPED" without giving further information on the error. We cannot improve the alignment if the pipeline is not working properly already.

**Comment by jluethi** [comment]
As Markus stated today, the big issue probably is not the actual alignment function, but the fact that images are not illumination corrected before the alignment. As Gabri told me, trying to align non-illumination corrected images also doesn't work for him. Thus, what's necessary is to put the alignment in a step after the illumination correction and allow it to use illumination corrected images.

**Comment by hackermd** [comment]
The `tmlib.workflow.corilla` and `tmlib.workflow.align` steps for calculation of illumination correction statistics and shifts for image registration and alignment, respectively, are currently run in parallel, since the parent "image_preprocessing" *stage* is defined as a `tmlib.workflow.workflow.ParallelWorkflowStage`. This would need to be changed to a `tmlib.workflow.workflow.SequentialWorkflowStage` by changing the value in `tmlib.workflow.canonical.CanonicalWorkflowDependencies.STAGE_MODES` from `"parallel"` to `"sequential"`. Alternatively, this attribute could be overridden in `tmlib.workflow.multiplexing.MultiplexingWorkflowDependencies.STAGE_MODES` to leave the behaviour of the *canonical* workflow unchanged (although this workflow has only one step at the moment so it doesn't really matter).

In addition, to use the illumination statistics calculated in `tmlib.workflow.corilla` step in the subsequent `tmlib.workflow.align` step, the `tmlib.workflow.align` would ideally have an additional optional "illumcorr" argument in `tmlib.workflow.align.args.AlignBatchArguments` (similar to `tmlib.workflow.align.illuminati.IlluminatiBatchArguments.illumcorr` and `tmlib.workflow.align.jterator.JteratorBatchArguments.illumcorr`). This then also needs to be handled in `tmlib.workflow.align.ImageRegistrator.create_batches()` and `tmlib.workflow.align.ImageRegistrator.run_jobs()`.

**Comment by hackermd** [comment]
I've implemented optional illumination correction of images in the align step: TissueMAPS/TmLibrary@6cc51db3bd3f61f9d5c0f8b52999599ccc206053.

Let's see whether this helps in achieving a robust alignment of images with low DAPI intensities.

**Comment by alecrimi** [comment]
If we load few files, and therefore we don't have the metafile. What are the relevant information I am missing? 
I see only
- vn_horizontal
- n_vertical
- regex
-stitch_layout
Which I thought I filled properly, but then I got this:

> JOB FAILED:
'ExperimentConnection' object has no attribute '_session'
  File "/home/ubuntu/tmlibrary/tmlib/workflow/cli.py", line 277, in __main__
    cli_instance(arguments)
  File "/home/ubuntu/tmlibrary/tmlib/workflow/cli.py", line 336, in __call__
    method(**method_args)
  File "/home/ubuntu/tmlibrary/tmlib/workflow/cli.py", line 367, in init
    api.delete_previous_job_output()
  File "/home/ubuntu/tmlibrary/tmlib/workflow/metaconfig/api.py", line 120, in delete_previous_job_output
    with tm.utils.ExperimentConnection(self.experiment_id) as connection:
  File "/home/ubuntu/tmlibrary/tmlib/models/utils.py", line 714, in __enter__
    self._set_search_path()
  File "/home/ubuntu/tmlibrary/tmlib/models/utils.py", line 728, in _set_search_path
    self._session.execute('''

It is because of the few images or strange parameter or there is a real problem.

**Comment by hackermd** [comment]
Your code is no longer up-to-date. Update TmLibrary and TmServer.

**Comment by alecrimi** [comment]
it worked as a charm 👍

**Comment by alecrimi** [comment]
Something is still missing or outdated. I got this during the alignment.

> JOB FAILED:
'Plate' object has no attribute 'cycles'
  File "/usr/local/lib/python2.7/dist-packages/tmlib/workflow/cli.py", line 277, in __main__
    cli_instance(arguments)
  File "/usr/local/lib/python2.7/dist-packages/tmlib/workflow/cli.py", line 336, in __call__
    method(**method_args)
  File "/usr/local/lib/python2.7/dist-packages/tmlib/workflow/cli.py", line 369, in init
    batches = api.create_batches(self._batch_args)
  File "/usr/local/lib/python2.7/dist-packages/tmlib/workflow/align/api.py", line 77, in create_batches
    if not(len(plate.cycles) > 1):

I am using only two cycles, so I set ref_cycle=0 and wavelength=1.

**Comment by hackermd** [comment]
Fixed with TissueMAPS/TmLibrary@051765850abc23c9f54cfe5a4dfb6cafe607d8c5

**Comment by alecrimi** [comment]
With this new fix, the names of the features are gone.
And the inspector is giving also this error:
GET http://130.60.24.212/images/ui-bg_highlight-soft_100_eeeeee_1x100.png 404 (NOT FOUND)

**Comment by hackermd** [comment]
@ggut Alignment seems to be robust with the prior illumination correction. Can we consider this issue to be solved?
